#!/usr/bin/env bash
#This script is displaying 9 best school and one Hi y and Best school
i=1
while :
do
   if [ $i -eq 10 ]; then
           break
   fi
   echo "Best School"
   ((i++))
done
echo Hi
echo "Best School"
