#!/usr/bin/env bash
#This script is displaying bad luck , good luck , best school
i=1
while [ $i -lt 11 ]
do
  if [ $i = 4 ]
then
echo "bad luck"
elif [ $i = 8 ]
then
  echo "good luck"
else
  echo "Best School"
fi
 let i+=1
done
